### ISSUE TITLE
RP2040 Failed to attach to RTT

### ISSUE THREAD

**Issue by Wertyuud** [lulf/embassy-template#3]
I generated new rp project using this template, and I tested it with rasperry pi pico and picoprobe. Main file contains defmt rtt logger, so I assume it should be working more or less out of the box, however I get the following error when started with cargo run.

```
(...)
    Finished release [optimized] target(s) in 31.67s
     Running `probe-rs run --chip RP2040 target\thumbv6m-none-eabi\release\cargo-generate-test3`
      Erasing ✔ [00:00:00] [###############################################] 16.00 KiB/16.00 KiB @ 60.10 KiB/s (eta 0s )
  Programming ✔ [00:00:00] [###############################################] 16.00 KiB/16.00 KiB @ 36.05 KiB/s (eta 0s )
    Finished in 0.744s
ERROR probe_rs::cmd::run: Failed to attach to RTT, continuing...
```

Logging is working correctly with modified files like below. I added manually BOOT2 to memory.x and line with Tlink-rp.x to build.rs

memory.x
```

MEMORY
{
  BOOT2   : ORIGIN = 0x10000000, LENGTH = 0x100
  FLASH : ORIGIN = 0x10000100, LENGTH = 2048K - 0x100
  RAM : ORIGIN = 0x20000000, LENGTH = 264K
}

```

build.rs
```
(...)
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    println!("cargo:rustc-env=DEFMT_LOG=info");
    println!("cargo:rustc-link-arg-bins=-Tlink-rp.x");
}

```

BTW I also noticed, that both build.rs and config.toml sets log filter DEFMT_LOG. Shouldn't it be configured in one place?

I haven't tried any other MCU target.

**Comment by lulf** [comment]
Thanks for the bug report! This should be fixed on main now. Removed the DEFMT_LOG from build.rs.
